### PR TITLE
Fix build process so data is correctly generated

### LINKED ISSUE #18: Github key should be enough to give information about a crate commits
In recent changes https://github.com/AeroRust/are-we-in-space-yet/pull/16 ( by @Adminixtrator ) a feature was added that shows a score, last commit, etc for a crate.

There is a problem when no `repository` key is added, even though there is a `github` key - no statistics is show for the repository.

The key `github` should be enough to extract the same information as from the `repository` one.

Screenshot from 2021-10-30 13-46-22

### PR DESCRIPTION
**Pull request by MoralCode**
this resolves #18 per my comment on that issue (remove the repository key and use the github key instead to deduplicate)

also fixes a 403 error that was preventing last_updated times from showing up for all crates

### CODE REVIEW

**Comment by elpiel** [comment]
Thank you for the PR!
Will this work for gitlab as well? `nyx-space` uses gitlab and I don't believe that the `github` key will contain a `gitlab` URL.

**Comment by MoralCode** [comment]
here is a preliminary/untested first-pass at adding gitlab support.

**Comment by MoralCode** [comment]
Screenshot_20220402_113809
Screenshot_20220402_113757

This should work now and properly generate data for both github and gitlab repos

To support a new repo type (like bitbucket for example), here are the steps:
- add a 120x120px bitbucket.png file containing the bitbucket logo to the images folder
- create a function similar to the existing two in the ruby plugin to query the bitbucker api for data and put it into values that the other APIs are using (like stargazers_count instead of stars_count, **this is tech debt to some degree so this may need to be standardized/cleaned up in future**)
- call that function in the if-else chain for detecting types, also set the URL
- add any custom bitbucket-only stuff in the template for generating the entries

**Comment by elpiel** [comment]
Ok, let's try this out.
I've added a GITLAB token for the deployment, so :crossed_fingers:

**Review by elpiel — APPROVED** [review]
Looks great, thank you so much!

**Pull request merged**
